### ISSUE TITLE
Switch API middleware to use the session cookies

### ISSUE THREAD

**Issue by beauraines** [beauraines/dog-walker#73]
Switch away from the token authentication so that the `user` object doesn't have to be passed to _every_ Vue component that is going to make an API call.

- [x] Change auth configuration to use passport.
- [x] Update the axios call parameters `Authorization: 'Bearer ' + this.user.api_token` probably isn't needed
https://github.com/beauraines/dog-walker/search?q=Authorization%3A+%27Bearer+%27+%2B+this.user.api_token&unscoped_q=Authorization%3A+%27Bearer+%27+%2B+this.user.api_token
- [x] Confirm edit functionality works
- [x] ~~Remove the user from the Vue component's `prop`~~ See https://github.com/beauraines/dog-walker/issues/73#issuecomment-626978706
- [x] Review and configure [Token lifetimes](https://laravel.com/docs/6.x/passport#token-lifetimes)

**Comment by cacpmw** [comment]
@beauraines this should be `passport` instead of `token`
https://github.com/beauraines/dog-walker/blob/7254205932cd877ac97fc6771d21515430761ee8/config/auth.php#L45

Of course you'd need to have passport installed:

`composer require laravel/passport`
`php artisan migrate`
`php artisan passport:install`

Then on `AuthServiceProvider@boot`:
```
        Passport::routes();
        Passport::personalAccessTokensExpireIn(now()->addMonths(6));
        Passport::personalAccessClientId(1);
```

The `User.php` needs a trait:
`use Laravel\Passport\HasApiTokens;`

`use HasApiTokens;`

After all that your protected routes on api.php should have the `auth:api` middleware

**Comment by beauraines** [comment]
Passport documentation https://laravel.com/docs/6.x/passport

**Comment by beauraines** [comment]
- [ ] Review [Token lifetimes](https://laravel.com/docs/6.x/passport#token-lifetimes)

**Comment by beauraines** [comment]
@cacpmw Thanks for the pointers! I was able to add Laravel Passport and make it work.

I do have a question about the Vue component from the package [PersonalAccessTokens.vue](https://github.com/beauraines/dog-walker/blob/ea6ba91289c126b77d9c57ceb1b3d81faccec92d/resources/js/components/passport/PersonalAccessTokens.vue#L1), [AuthorizedClients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/AuthorizedClients.vue), [Clients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/Clients.vue). Do I actually _need_ these files, if I'm only using the tokens for _my_ API in the front end (no mobile or external access).

These came from the [Front End Quickstart](https://laravel.com/docs/6.x/passport#frontend-quickstart) part of the documentation.

**Comment by beauraines** [comment]
@cacpmw and I lost everything because of rebase gone wrong.... My question still stands, but as of this moment the PHP portion of the setup is gone, so it's not working. Ugh.

**Comment by beauraines** [comment]
@cacpmw Okay, I fixed the lost code and its all working again. I almost lost it during rebase, I'm not sure what is happening there, but oh well.

One more question.

https://github.com/beauraines/dog-walker/blob/42213c84e9c9cf6009ed15f1a10d7bf47c8c8211/app/Providers/AuthServiceProvider.php#L30

why is this _always_ using the 1 as opposed to something dynamic?

**Comment by beauraines** [comment]
Note for future self, I'm not going to change the token expirations because I don't understand why they should be any shorter...

**Comment by beauraines** [comment]
Removing the user from the component's prop is a bigger thing than I was thinking...

The user object comes from the blade - every blade has it. If the front end is going to be solely Vue based, 6be9ab443ee3c1af7b8f8dee44743b6ccd1f2bbb should be undone and Vue should pull the user object. 

This needs to be re-thought next week.

**Comment by beauraines** [comment]
I'm not going to remove the user from the Vue's `prop`.  If I were to not do that, each component would make an API call for the `user` object, which would be inefficient. If a component needs it, it can either get it from the blade or, in really nested circumstances, directly.

**Comment by beauraines** [comment]
The booking edit function _is_ broken. It is part of the `api` routing so it **now** must be vue based (axios really, so that the token gets passed properly).   Right now, a PUT `api/booking/###` gets 302 redirected to the login page, because the request is not authenticated.

**Comment by beauraines** [comment]
Next steps

TODO
    1. Confirm works with Staff user type
    2. GET api/client is throwing a 403 (Forbidden) AccessDeniedHTTPException

**Comment by beauraines** [comment]
> 
> I do have a question about the Vue component from the package [PersonalAccessTokens.vue](https://github.com/beauraines/dog-walker/blob/ea6ba91289c126b77d9c57ceb1b3d81faccec92d/resources/js/components/passport/PersonalAccessTokens.vue#L1), [AuthorizedClients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/AuthorizedClients.vue), [Clients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/Clients.vue). Do I actually _need_ these files, if I'm only using the tokens for _my_ API in the front end (no mobile or external access).
> 
> These came from the [Front End Quickstart](https://laravel.com/docs/6.x/passport#frontend-quickstart) part of the documentation.

@cacpmw I don't think I need these, because the only access _users_ will have is through the app and I can generate tokens from the command line for my own testing purposes. Does that make sense?

**Comment by cacpmw** [comment]
> @cacpmw Okay, I fixed the lost code and its all working again. I almost lost it during rebase, I'm not sure what is happening there, but oh well.
> 
> One more question.
> 
> https://github.com/beauraines/dog-walker/blob/42213c84e9c9cf6009ed15f1a10d7bf47c8c8211/app/Providers/AuthServiceProvider.php#L30
> 
> why is this _always_ using the 1 as opposed to something dynamic?

Because it is usually the one with id number 1 unless the table is messed up. But you fetch it on database and then pass the id.

**Comment by cacpmw** [comment]
> @cacpmw Thanks for the pointers! I was able to add Laravel Passport and make it work.
> 
> I do have a question about the Vue component from the package [PersonalAccessTokens.vue](https://github.com/beauraines/dog-walker/blob/ea6ba91289c126b77d9c57ceb1b3d81faccec92d/resources/js/components/passport/PersonalAccessTokens.vue#L1), [AuthorizedClients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/AuthorizedClients.vue), [Clients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/Clients.vue). Do I actually _need_ these files, if I'm only using the tokens for _my_ API in the front end (no mobile or external access).
> 
> These came from the [Front End Quickstart](https://laravel.com/docs/6.x/passport#frontend-quickstart) part of the documentation.

These aren't truly necessary. It is just a convenience to manage your application tokens. I never used them nor have I created them.

**Comment by cacpmw** [comment]
> Note for future self, I'm not going to change the token expirations because I don't understand why they should be any shorter...

I'd like to have the option to make tokens that never expire

**Comment by cacpmw** [comment]
> The booking edit function _is_ broken. It is part of the `api` routing so it **now** must be vue based (axios really, so that the token gets passed properly). Right now, a PUT `api/booking/###` gets 302 redirected to the login page, because the request is not authenticated.

You need to have the user token saved on the store with vuex or some other method and then send the `authorization header` for every request. Under `resources/js/bootstrap.js` there you can find an example of how to automatically add headers to every request

**Comment by cacpmw** [comment]
> > I do have a question about the Vue component from the package [PersonalAccessTokens.vue](https://github.com/beauraines/dog-walker/blob/ea6ba91289c126b77d9c57ceb1b3d81faccec92d/resources/js/components/passport/PersonalAccessTokens.vue#L1), [AuthorizedClients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/AuthorizedClients.vue), [Clients.vue](https://github.com/beauraines/dog-walker/blob/master/resources/js/components/passport/Clients.vue). Do I actually _need_ these files, if I'm only using the tokens for _my_ API in the front end (no mobile or external access).
> > These came from the [Front End Quickstart](https://laravel.com/docs/6.x/passport#frontend-quickstart) part of the documentation.
> 
> @cacpmw I don't think I need these, because the only access _users_ will have is through the app and I can generate tokens from the command line for my own testing purposes. Does that make sense?

Sure. I've never even seen those before your posting. I think they are just for convenience. But I will starting using them. It seems very convenient for revoking tokens

**Comment by beauraines** [comment]
> > The booking edit function _is_ broken. It is part of the `api` routing so it **now** must be vue based (axios really, so that the token gets passed properly). Right now, a PUT `api/booking/###` gets 302 redirected to the login page, because the request is not authenticated.
> 
> You need to have the user token saved on the store with vuex or some other method and then send the `authorization header` for every request. Under `resources/js/bootstrap.js` there you can find an example of how to automatically add headers to every request

Yeah, I had originally wrote the code to have a Laravel Form post the data from a blade for editing only, so I needed to migrate the blade/form to Vue components and my axios API call.

**Comment by beauraines** [comment]
> > @cacpmw Okay, I fixed the lost code and its all working again. I almost lost it during rebase, I'm not sure what is happening there, but oh well.
> > One more question.
> > https://github.com/beauraines/dog-walker/blob/42213c84e9c9cf6009ed15f1a10d7bf47c8c8211/app/Providers/AuthServiceProvider.php#L30
> > 
> > why is this _always_ using the 1 as opposed to something dynamic?
> 
> Because it is usually the one with id number 1 unless the table is messed up. But you fetch it on database and then pass the id.

So, the "client" represents the app that is doing the authentication. Why would I ever have more than one?

**Comment by cacpmw** [comment]
> > > @cacpmw Okay, I fixed the lost code and its all working again. I almost lost it during rebase, I'm not sure what is happening there, but oh well.
> > > One more question.
> > > https://github.com/beauraines/dog-walker/blob/42213c84e9c9cf6009ed15f1a10d7bf47c8c8211/app/Providers/AuthServiceProvider.php#L30
> > > 
> > > why is this _always_ using the 1 as opposed to something dynamic?
> > 
> > 
> > Because it is usually the one with id number 1 unless the table is messed up. But you fetch it on database and then pass the id.
> 
> So, the "client" represents the app that is doing the authentication. Why would I ever have more than one?

you might wanna have a web client, a mobile client etc...
